/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



typedef volatile unsigned int vuint32_t ;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

//PORTA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *(vuint32_t *)(GPIOA_BASE + 0x0)
#define GPIOA_CRH *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_IDR *(vuint32_t *)(GPIOA_BASE + 0x08)
#define GPIOA_ODR *(vuint32_t *)(GPIOA_BASE + 0x0C)
//PORTB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *(vuint32_t *)(GPIOB_BASE + 0x0)
#define GPIOB_CRH *(vuint32_t *)(GPIOB_BASE + 0x04)
#define GPIOB_IDR *(vuint32_t *)(GPIOB_BASE + 0x08)
#define GPIOB_ODR *(vuint32_t *)(GPIOB_BASE + 0x0C)

#define RCC_BASE 0x40021000
//APB2 peripheral clock enable register (RCC_APB2ENR)
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE+ 0x18)
#define RCC_CFGR *(vuint32_t *)(RCC_BASE+ 0x04)

void clock_init(void)
{
	//Bit 2 IOPAEN: IO port A clock enable
	//Set and cleared by software.
	//0: IO port A clock disabled
	//1: IO port A clock enabled
	RCC_APB2ENR |=(1<<2);

	//Bit 3 IOPBEN: IO port B clock enable
	//Set and cleared by software.
	//0: IO port B clock disabled
	//1: IO port B clock enabled
	RCC_APB2ENR |=(1<<3);
}

void Gpio_init(void)
{
	GPIOB_CRL=0;
	GPIOB_CRH=0;

	GPIOA_CRL=0;
	GPIOA_CRH=0;
	//PORTB pin1 to be output push-pull mode
	//Output mode, max speed 10 MHz
	GPIOB_CRL |=(1<<4);

	//PORTA pin1 to be input highZ
	GPIOA_CRL |=(1<<6);
	//PORTA pin13 to be input highZ
	GPIOA_CRH |=(1<<22);

	//PORTB pin13 to be output push-pull mode
	//Output mode, max speed 10 MHz
	GPIOB_CRH |=(1<<20);
}

void wait(unsigned int x)

{
	unsigned int i,j;
	for(i=0;i<x;i++)
		for(j=0;j<255;j++);

}


int main(void)
{

	clock_init();
	Gpio_init();



	while(1)
	{

		if( (GPIOA_IDR &(1<<1))>>1 == 0) //pull-up true means pressed
		{
			GPIOB_ODR ^=(1<<1);
			while((GPIOA_IDR &(1<<1))>>1 == 0);//single press
		}

		if((GPIOA_IDR &(1<<13))>>13 == 1)//pull-down true means pressed
		{
			GPIOB_ODR ^=(1<<13);

		}
		wait(3);


	}

}

