/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */



#include"Platforms_Types.h"
#define RCC_BASE 0x40021000
#define PORTA_BASE 0x40010800
#define RCC_APB2ENR *((vuint32_t*)(RCC_BASE+0x18))

#define GPIOA_CRH *((vuint32_t*)(PORTA_BASE+0x04))
#define GPIOA_ODR  *((vuint32_t*)(PORTA_BASE+0x0C))


////////////////////////////////
typedef union{
	vuint32_t all_fields;
	struct{
		vuint32_t reserved:13;
		vuint32_t p_13:1;
	}pin;


}R_ODR_t;

volatile R_ODR_t* R_ODR= (volatile R_ODR_t*)(PORTA_BASE+0x0C);
//////////////////////////////////

int main()
{
	RCC_APB2ENR |=(1<<2);
	GPIOA_CRH &=0xff0fffff; //writing zeros on (20-->23) and maintaining the other bits
	GPIOA_ODR |=0x00200000; //then writing 2 on(20-->23)

	while(1)
	{
		//GPIOA_ODR |=(1<<13);
		R_ODR->pin.p_13=1;
		for(int i=0;i<6000;i++);
		//GPIOA_ODR &=~(1<<13);
		R_ODR->pin.p_13=0;
		for(int i=0;i<6000;i++);

	}

	return 0;
}
