/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include"stm32f103x8_gpio_driver.h"


int main(void)
{
	//ENABLE PORT A,B CLOCK
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();

	GPIO_PinConfig_t PinCFG;

	//PA1 INPUT HighZ
	PinCFG.GPIO_PinNumber=GPIO_PIN_1;
	PinCFG.GPIO_MODE=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCFG);

	//PA13 INPUT HighZ
	PinCFG.GPIO_PinNumber=GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOA, &PinCFG);

	//PB1 output push-pull mode
	PinCFG.GPIO_PinNumber=GPIO_PIN_1;
	PinCFG.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	PinCFG.GPIO_Output_Speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

	//PB13 output push-pull mode
	PinCFG.GPIO_PinNumber=GPIO_PIN_13;
	MCAL_GPIO_Init(GPIOB, &PinCFG);

   while(1)
   {
	   if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)==0)//pressed
	   {
		   MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
		   while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1)==0);//single press
	   }

	   if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13)==1)//pressed
	  	   {
	  		   MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);//multi press

	  	   }

   }


}
