/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



//Learn-in-depth
//Keroles Shenouda
//Mastering_Embedded System online diploma
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

#include "STM32F103x8.h"
#include "stm32f103x8_gpio_driver.h"
#include "stm32f103x8_EXTI_driver.h"
#include "lcd.h"


unsigned int IRQ_flag=0;


void wait (uint32_t time) {
	uint32_t i, j;
	for (i = 0; i < time; i++)
		for (j = 0; j < 255; j++);
}

void EXTI9_CallBack(void)
{
	IRQ_flag=1;
	LCD_WRITE_STRING("IRQ EXTI is happend _|-");
	wait(1000);
}


int main(void)
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
	LCD_INIT();
	LCD_clear_screen();


	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN=EXTI9PB9;
	EXTI_CFG.Trigger_Case=EXTI_Trigger_RISING;
	EXTI_CFG.P_IRQ_CallBack=EXTI9_CallBack;
	EXTI_CFG.IRQ_EN=EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	IRQ_flag=1;




	/* Loop forever */
	while(1)
	{
		if(IRQ_flag)
		{
			LCD_clear_screen();
			IRQ_flag=0;

		}


	}

}
